Backend: Vivado
ClockPeriod: 5
HLSConfig:
  Model:
    Precision: ap_fixed<16,6>
    ReuseFactor: 1
IOType: io_parallel
KerasH5: keras/KERAS_3layer_weights.h5
KerasJson: keras/KERAS_3layer.json
OutputDir: my-hls-test
ProjectName: myproject
Stamp: 5aC1daf3
XilinxPart: xcvu9p-flga2104-2L-e
